name: Build

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_NAME: nomad-logger

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
